### ISSUE TITLE
2021/08/31 23:19:57 429 Too Many Requests

### ISSUE THREAD

**Issue by otiai10** [otiai10/gh-dependents#2]
```sh
gh dependents -v moby/moby
# ...
[Page  58] https://github.com/moby/moby/network/dependents?dependents_after=MTY0NTUyODc1NzA	= 1498
[Page  59] https://github.com/moby/moby/network/dependents?dependents_after=MTY0NDI5OTIzOTQ	= 1528
[Page  60] https://github.com/moby/moby/network/dependents?dependents_after=MTY0NDI5Njg3OTc	= 1558
[Page  61] https://github.com/moby/moby/network/dependents?dependents_after=MTY0NDI5MzM4OTQ	= 1588
[Page  62] https://github.com/moby/moby/network/dependents?dependents_after=MTY0NDI4NTk2NzE2021/08/31 23:19:57 429 Too Many Requests
$
```

**Comment by peteos123** [comment]
> ```shell
> gh závislé osoby -v moby/moby
> # ...
> [Strana 58] https://github.com/moby/moby/network/dependents?dependents_after=MTY0NTUyODc1NzA = 1498
> [Strana 59] https://github.com/moby/moby/network/dependents?dependents_after=MTY0NDI5OTIzOTQ = roku 1528
> [Strana 60] https://github.com/moby/moby/network/dependents?dependents_after=MTY0NDI5Njg3OTc = 1558
> [Strana 61] https://github.com/moby/moby/network/dependents?dependents_after=MTY0NDI5MzM4OTQ = 1588
> [Strana 62] https://github.com/moby/moby/network/dependents?dependents_after=MTY0NDI4NTk2NzE2021/08/31 23:19:57 429 Príliš Veľa Žiadostí
> $
> ```

**Comment by otiai10** [comment]
Thanks. I understand you reproduced this problem in your usecase, is it right?
@peteos123
