### ISSUE TITLE
Specify offset in request

### ISSUE THREAD

**Issue by brandongregoryscott** [otiai10/gh-dependents#3]
Hey there!

Thanks for building out this extension, it's awesome. One thing that I would love the ability to do is to start from a specific page offset (what looks like the `dependents_after` query param in the UI) For analyzing a larger repo, the current rate limiting back off might not be enough - it seems to bust at around page 30-40 for me. I'm wondering how much effort it would be to plumb through a command line flag to set the starting `dependents_after` value so it can pick up from a previous cursor. 

(Side note: I just noticed there's a package vs. repository filter on the Network Dependents page - would that be simple enough to wire up, too?)

**Comment by otiai10** [comment]
I like the idea too.
Let me know some repos which I can test your scenario.

**Comment by otiai10** [comment]
@brandongregoryscott 
Released under v0.1.0. Please try
```
gh extension upgrade otiai10/gh-dependetns
```
to get the latest bin. Please let me know if you find any issues or bugs. Super appreciated.

**Comment by brandongregoryscott** [comment]
Thanks for the quick turnaround @otiai10! It seems to work as intended. I've been trying to analyze the dependents of https://github.com/eslint/eslint, which has millions of repository dependents and ~400k package dependents. The scale of this might just be too big to crawl 30 results at a time without a sorting query param which I don't think is available 😭
